export const TYPES = {
    ADD_TO_CART: "ADD_TO_CART",
    ADD_TOT_CART: "ADD_TOT_CART",
    TOGGLE_AMOUNT: "TOGGLE_AMOUNT",
    REMOVE_TOT_CART: "REMOVE_TOT_CART",
    REMOVE_ONE_FROM_CART: "REMOVE_ONE_FROM_CART",
    REMOVE_ALL_FROM_CART: "REMOVE_ALL_FROM_CART",
    CLEAR_CART: "CLEAR_CART",
};